version: '3.7'

networks:
  bigdata_network:
    driver: bridge
    external: true

services:  
  jobmanager:
    build:
      context: .
      dockerfile: ./docker/files/Dockerfile-flink
    container_name: flink-jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ~/bigdata_platform/jars:/opt/flink/usrlib
    networks:
      - bigdata_network

  taskmanager:
    build:
      context: .
      dockerfile: ./docker/files/Dockerfile-flink
    container_name: flink-taskmanager
    hostname: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - bigdata_network
  