FROM hseeberger/scala-sbt:8u222_1.3.5_2.13.1

WORKDIR /app

RUN mkdir -p /root/.sbt/1.0/plugins && \
    echo 'addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "1.1.0")' > /root/.sbt/1.0/plugins/plugins.sbt
