#Version funcional pero sin la libreria kafka-scala

FROM jupyter/all-spark-notebook:latest

# Instala/verifica kernel Scala (Apache Toree)  
RUN pip install --no-cache-dir toree && \  
    jupyter toree install --user && \  
    jupyter kernelspec list


RUN /bin/bash -c "source /opt/conda/bin/activate base && pip install kafka-python"
RUN wget https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.2.1/kafka-clients-2.2.1.jar -P /home/jovyan/.local/share/jupyter/kernels/apache_toree_scala/lib/

USER root
RUN mkdir -p /opt/spark/jars/
RUN wget https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.2.1/kafka-clients-2.2.1.jar -P /opt/spark/jars/
RUN apt update && apt install -y iputils-ping

USER jovyan





#RUN echo '{"argv": ["/opt/conda/bin/scala", "-classpath", "/path/to/kafka-clients-2.2.1.jar", "-jar", "/opt/conda/lib/python3.11/site-packages/toree-assembly-0.5.0-incubating.jar"], "display_name": "Scala (Apache Toree)", "language": "scala"}' > ~/.local/share/jupyter/kernels/apache_toree_scala/kernel.json



#No funciona
#Probando con conda
#FROM jupyter/all-spark-notebook:latest
#RUN /bin/bash -c "source /opt/conda/bin/activate base && pip install kafka-python"
#RUN conda install -c conda-forge scala
#RUN pip install toree
#RUN jupyter toree install --user
#RUN wget https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.2.1/kafka-clients-2.2.1.jar -P /tmp && \
#    mv /tmp/kafka-clients-2.2.1.jar /opt/conda/lib/python3.11/site-packages/
# Configurar el kernel.json
#RUN echo '{"argv": ["/opt/conda/bin/scala", "-classpath", "/opt/conda/lib/python3.11/site-packages/kafka-clients-2.2.1.jar", "-jar", "/opt/conda/lib/python3.11/site-packages/toree-assembly-0.5.0-incubating.jar"], "display_name": "Scala (Apache Toree)", "language": "scala"}' > ~/.local/share/jupyter/kernels/apache_toree_scala/kernel.json



