FROM apache/hadoop:3.3.6
USER root

RUN mkdir -p /hadoop/{dfs/name,yarn/logs} /opt/hadoop/etc/hadoop && \
    chown -R hadoop:hadoop /hadoop /opt/hadoop/etc/hadoop && \
    chmod -R 775 /opt/hadoop/etc/hadoop && \
    rm -f /opt/hadoop/etc/hadoop/*.raw  # 👈 Elimina .raw ANTES de copiar

COPY ./docker/compose/configs/ /opt/hadoop/etc/hadoop/

USER hadoop
