#Version funcional pero sin la libreria kafka-scala

FROM jupyter/all-spark-notebook:latest

# Instala/verifica kernel Scala (Apache Toree)  
RUN pip install --no-cache-dir toree && \  
    jupyter toree install --user && \  
    jupyter kernelspec list


RUN /bin/bash -c "source /opt/conda/bin/activate base && pip install kafka-python"
RUN wget https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.2.1/kafka-clients-2.2.1.jar -P /home/jovyan/.local/share/jupyter/kernels/apache_toree_scala/lib/

USER root
RUN mkdir -p /opt/spark/jars/
RUN wget https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.2.1/kafka-clients-2.2.1.jar -P /opt/spark/jars/

#Bibliotecas
#RUN apt update && apt install -y iputils-ping
#RUN pip install faker

#RUN pip install psycopg2


# Instala las bibliotecas necesarias (como iputils-ping, faker y psycopg2)
RUN apt update && apt install -y iputils-ping libpq-dev
RUN pip install faker

# Instalar psycopg2, con las dependencias necesarias (libpq-dev)
RUN pip install psycopg2
RUN pip install mysql-connector-python

# Alternativa sin las dependencias si prefieres usar psycopg2-binary (opcional)
# RUN pip install psycopg2-binary


USER jovyan

